"""tenor — a fixed-income curve toolkit, in pure Python with no dependencies."""

from __future__ import annotations

from .bond import Accrual, BadBond, Bond, Cashflow
from .bootstrap import BootstrapFailed, Bootstrapped, bootstrap
from .calendar import WEEKENDS_ONLY, Calendar, Rolling, calendar_from
from .curve import (
    BadCurve,
    DiscountCurve,
    Interpolation,
    OffCurve,
    Pillar,
    flat_curve,
)
from .daycount import (
    BadPeriod,
    Basis,
    day_count,
    days_in_year,
    denominator,
    is_end_of_february,
    is_leap,
    year_fraction,
)
from .instruments import (
    BadInstrument,
    Deposit,
    Future,
    Instrument,
    Swap,
    ho_lee_convexity,
    maturity_of,
    start_of,
)
from .lattice import (
    BadLattice,
    Exercise,
    Lattice,
    lattice_price,
    option_adjusted_spread,
    option_cost,
    steps_between,
)
from .monotone import (
    MonotoneConvex,
    NotMonotone,
    Region,
    Segment,
    classify,
    node_forwards,
)
from .rates import (
    BadRate,
    Compounding,
    Rate,
    convert,
    discount_factor,
    forward_rate,
    rate_from_discount,
)
from .risk import (
    BadRisk,
    Bucket,
    InstrumentRisk,
    KeyRate,
    buckets_from,
    bumped,
    curvature,
    instrument_risk,
    key_rates,
    level,
    shape_duration,
    shifted_by,
    slope,
    tent_weights,
    total_instrument_risk,
)
from .schedule import (
    BadSchedule,
    Frequency,
    Period,
    Schedule,
    Stub,
    add_months,
    end_of_month,
    generate,
)
from .solve import NoRoot, Root, bracket_root, brent, solve
from .spread import (
    BadSpread,
    discounted_with_spread,
    i_spread,
    par_rate_at,
    z_spread,
)

__version__ = "0.1.0"

__all__ = [
    "WEEKENDS_ONLY",
    "Accrual",
    "BadBond",
    "BadCurve",
    "BadInstrument",
    "BadLattice",
    "BadPeriod",
    "BadRate",
    "BadRisk",
    "BadSchedule",
    "BadSpread",
    "Basis",
    "Bond",
    "BootstrapFailed",
    "Bootstrapped",
    "Bucket",
    "Calendar",
    "Cashflow",
    "Compounding",
    "Deposit",
    "DiscountCurve",
    "Exercise",
    "Frequency",
    "Future",
    "Instrument",
    "InstrumentRisk",
    "Interpolation",
    "KeyRate",
    "Lattice",
    "MonotoneConvex",
    "NoRoot",
    "NotMonotone",
    "OffCurve",
    "Period",
    "Pillar",
    "Rate",
    "Region",
    "Rolling",
    "Root",
    "Schedule",
    "Segment",
    "Stub",
    "Swap",
    "__version__",
    "add_months",
    "bootstrap",
    "bracket_root",
    "brent",
    "buckets_from",
    "bumped",
    "calendar_from",
    "classify",
    "convert",
    "curvature",
    "day_count",
    "days_in_year",
    "denominator",
    "discount_factor",
    "discounted_with_spread",
    "end_of_month",
    "flat_curve",
    "forward_rate",
    "generate",
    "ho_lee_convexity",
    "i_spread",
    "instrument_risk",
    "is_end_of_february",
    "is_leap",
    "key_rates",
    "lattice_price",
    "level",
    "maturity_of",
    "node_forwards",
    "option_adjusted_spread",
    "option_cost",
    "par_rate_at",
    "rate_from_discount",
    "shape_duration",
    "shifted_by",
    "slope",
    "solve",
    "start_of",
    "steps_between",
    "tent_weights",
    "total_instrument_risk",
    "year_fraction",
    "z_spread",
]
